name: frutiapp_web
description: "FrutiApp Web - Laboratorio 1, IF0009 Desarrollo de Software IV"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.13.1 <4.0.0'
  flutter: '>=3.35.1'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  file_selector: ^1.1.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
